export { default as mainImage } from "assets/img/main_image.png";
export { default as o_slack } from "assets/img/o_slack.png";
export { default as google } from "assets/img/google.png";
export { default as jandi } from "assets/img/jandi.png";
export { default as kakao } from "assets/img/kakao.png";
export { default as discord } from "assets/img/discord.png";
export { default as gmail } from "assets/img/gmail.png";
export { default as add } from "assets/img/add.png";
export { default as slack } from "assets/img/slack.png";
